"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {ArrowLeft,RefreshCw} from "lucide-react";import {Button} from "@/components/ui/button";import {Badge} from "@/components/ui/badge";
type Item=Record<string,string|number|null>;
export function AssessmentQueue(){
 const [items,setItems]=useState<Item[]>([]);const [error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/payroll/applications");if(r.status===401){window.location.href="/portal";return}const b=await r.json();if(!r.ok){setError(b.error||"Data tidak dapat dimuat");return}setItems(b.applications)};
 useEffect(()=>{void load()},[]);
 return <div className="container-pro py-10"><div className="flex items-end justify-between gap-4"><div><Button asChild variant="ghost" className="mb-4"><Link href="/admin/payroll"><ArrowLeft/>Admin Dashboard</Link></Button><p className="text-xs font-bold uppercase tracking-wider text-orange">MSG Risk Operations</p><h1 className="mt-2 text-3xl font-bold">Assessment Queue</h1></div><Button variant="outline" onClick={load}><RefreshCw/>Refresh</Button></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-8 grid gap-4">{items.map(i=>{const company=JSON.parse(String(i.company_json));return <div key={String(i.id)} className="grid gap-4 rounded-2xl border bg-card p-5 md:grid-cols-[1.3fr_.7fr_.7fr_auto] md:items-center"><div><p className="font-semibold">{company.legalName}</p><p className="text-xs text-muted-foreground">{i.registration_number}</p></div><Badge variant="secondary">{String(i.status).replaceAll("_"," ")}</Badge><p className="font-bold">{i.due_diligence_score??"Not run"}</p><Button asChild><Link href={`/admin/assessment/${i.id}`}>Open Assessment</Link></Button></div>})}</div></div>
}
